### ISSUE TITLE
Error : Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by antoinevastel** [plaperdr/fp-central#3]
Hi, I am using Brave browser and I have an error when i run the fingerprinting script. The full trace is : 

Uncaught TypeError: Cannot read property '0' of undefined 
audioContext.js:37

It seems to happen because of Brave's shield against browser fingerprinting. However, it makes it impossible then to send the data to the server.

Regards,

Antoine VASTEL

**Comment by plaperdr** [comment]
Thank you for bringing this bug to my attention! I just fixed it in commit 6df45fa7ef03be33f3a7b7f1030a45f82846ccee.
After looking at the Brave browser, they define what functions are blocked in the following [file](https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/content/scripts/blockCanvasFingerprinting.js). The "getChannelData" is indeed blocked when the fingerprinting protection is active and the script crashed as I wanted to read data from an undefined object.
